// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -source=event.go -destination=mocks/mock_event.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/yuryalencar/research-events/internal/model"
	repository "github.com/yuryalencar/research-events/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// FindActiveBySlug mocks base method.
func (m *MockEventRepository) FindActiveBySlug(ctx context.Context, slug string) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveBySlug", ctx, slug)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveBySlug indicates an expected call of FindActiveBySlug.
func (mr *MockEventRepositoryMockRecorder) FindActiveBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveBySlug", reflect.TypeOf((*MockEventRepository)(nil).FindActiveBySlug), ctx, slug)
}

// ListEvents mocks base method.
func (m *MockEventRepository) ListEvents(ctx context.Context, filter repository.ListEventsFilter) ([]model.Event, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, filter)
	ret0, _ := ret[0].([]model.Event)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockEventRepositoryMockRecorder) ListEvents(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockEventRepository)(nil).ListEvents), ctx, filter)
}

// Submit mocks base method.
func (m *MockEventRepository) Submit(ctx context.Context, event model.Event, deadlines []model.Deadline, submitter model.User) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, event, deadlines, submitter)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockEventRepositoryMockRecorder) Submit(ctx, event, deadlines, submitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockEventRepository)(nil).Submit), ctx, event, deadlines, submitter)
}
