// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -source=event.go -destination=mocks/mock_event.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/yuryalencar/research-events/internal/model"
	repository "github.com/yuryalencar/research-events/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepository is a mock of EventRepository interface.
type MockEventRepository struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepositoryMockRecorder
	isgomock struct{}
}

// MockEventRepositoryMockRecorder is the mock recorder for MockEventRepository.
type MockEventRepositoryMockRecorder struct {
	mock *MockEventRepository
}

// NewMockEventRepository creates a new mock instance.
func NewMockEventRepository(ctrl *gomock.Controller) *MockEventRepository {
	mock := &MockEventRepository{ctrl: ctrl}
	mock.recorder = &MockEventRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepository) EXPECT() *MockEventRepositoryMockRecorder {
	return m.recorder
}

// AddDeadlines mocks base method.
func (m *MockEventRepository) AddDeadlines(ctx context.Context, event model.Event, deadlines []model.Deadline, submitter model.User, auditAction model.AuditAction) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDeadlines", ctx, event, deadlines, submitter, auditAction)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddDeadlines indicates an expected call of AddDeadlines.
func (mr *MockEventRepositoryMockRecorder) AddDeadlines(ctx, event, deadlines, submitter, auditAction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDeadlines", reflect.TypeOf((*MockEventRepository)(nil).AddDeadlines), ctx, event, deadlines, submitter, auditAction)
}

// CancelDeadline mocks base method.
func (m *MockEventRepository) CancelDeadline(ctx context.Context, event model.Event, deadline model.Deadline, submitter model.User) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelDeadline", ctx, event, deadline, submitter)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelDeadline indicates an expected call of CancelDeadline.
func (mr *MockEventRepositoryMockRecorder) CancelDeadline(ctx, event, deadline, submitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelDeadline", reflect.TypeOf((*MockEventRepository)(nil).CancelDeadline), ctx, event, deadline, submitter)
}

// FindActiveBySlug mocks base method.
func (m *MockEventRepository) FindActiveBySlug(ctx context.Context, slug string) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveBySlug", ctx, slug)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveBySlug indicates an expected call of FindActiveBySlug.
func (mr *MockEventRepositoryMockRecorder) FindActiveBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveBySlug", reflect.TypeOf((*MockEventRepository)(nil).FindActiveBySlug), ctx, slug)
}

// FindByID mocks base method.
func (m *MockEventRepository) FindByID(ctx context.Context, id uint) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockEventRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEventRepository)(nil).FindByID), ctx, id)
}

// FindDeadlineByID mocks base method.
func (m *MockEventRepository) FindDeadlineByID(ctx context.Context, eventID, deadlineID uint) (model.Deadline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDeadlineByID", ctx, eventID, deadlineID)
	ret0, _ := ret[0].(model.Deadline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDeadlineByID indicates an expected call of FindDeadlineByID.
func (mr *MockEventRepositoryMockRecorder) FindDeadlineByID(ctx, eventID, deadlineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDeadlineByID", reflect.TypeOf((*MockEventRepository)(nil).FindDeadlineByID), ctx, eventID, deadlineID)
}

// ListEvents mocks base method.
func (m *MockEventRepository) ListEvents(ctx context.Context, filter repository.ListEventsFilter) ([]model.Event, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, filter)
	ret0, _ := ret[0].([]model.Event)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockEventRepositoryMockRecorder) ListEvents(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockEventRepository)(nil).ListEvents), ctx, filter)
}

// Submit mocks base method.
func (m *MockEventRepository) Submit(ctx context.Context, event model.Event, deadlines []model.Deadline, submitter model.User) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Submit", ctx, event, deadlines, submitter)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Submit indicates an expected call of Submit.
func (mr *MockEventRepositoryMockRecorder) Submit(ctx, event, deadlines, submitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockEventRepository)(nil).Submit), ctx, event, deadlines, submitter)
}

// SupersedeDeadline mocks base method.
func (m *MockEventRepository) SupersedeDeadline(ctx context.Context, event model.Event, oldDeadline, newDeadline model.Deadline, submitter model.User) (model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupersedeDeadline", ctx, event, oldDeadline, newDeadline, submitter)
	ret0, _ := ret[0].(model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SupersedeDeadline indicates an expected call of SupersedeDeadline.
func (mr *MockEventRepositoryMockRecorder) SupersedeDeadline(ctx, event, oldDeadline, newDeadline, submitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupersedeDeadline", reflect.TypeOf((*MockEventRepository)(nil).SupersedeDeadline), ctx, event, oldDeadline, newDeadline, submitter)
}
